### ISSUE TITLE
Compiled view generate unreachable code

### ISSUE THREAD

**Issue by lbarman** [hmil/topside#17]
When I compile a view, now `ts-node` complains that some code is unreachable and refuses to launch:
```/home/jwhite/.nvm/versions/node/v8.9.4/lib/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/view/transaction/edit.top.ts(67,5): error TS7027: Unreachable code detected.

    at createTSError (/home/jwhite/.nvm/versions/node/v8.9.4/lib/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/home/jwhite/.nvm/versions/node/v8.9.4/lib/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/home/jwhite/.nvm/versions/node/v8.9.4/lib/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/home/jwhite/.nvm/versions/node/v8.9.4/lib/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/jwhite/.nvm/versions/node/v8.9.4/lib/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
```
Sources:
[edit.top.html.txt](https://github.com/hmil/topside/files/2492415/edit.top.html.txt)
[edit.top.ts.txt](https://github.com/hmil/topside/files/2492416/edit.top.ts.txt)

My ts-node version:
```ts-node -v
ts-node v7.0.1
node v8.9.4
typescript v2.6.1
```

**Comment by hmil** [comment]
Thats fixable. The `conditionals` rule generates an [iife](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression) with a return statement at the end, regardless of whether there was an `else` statement in that block.

Maybe the `else` could be considered as the `default` value of the whole conditional. Then the conditional either ends in `return "";` or in `return [body of the else statement]`.

**Comment by lbarman** [comment]
Hmm might be simple, but if we have (simplified):
`IfFragment` as `(function(){ if(EXPR){ return (" `
`ElseIfFragment` as `"); } else if (EXPR2) { return ("`
`ElseFragment` as `"); } return ("` <-- changed following your remark
`EndIfFragment` as `"); } return "";}());"`

Now `EndIfFragment` is invalid; it must behave conditionally if it closes a simple `IfFragment` (which opened a if-block, and is waiting for `"); } return "";`) or if if follows a `ElseFragment` (which already closed the if-block, and only expects `"); })();`

Not familiar with compilers, is it possible to have conditional rules or is it against the design ?

**Comment by hmil** [comment]
The `context` is what I use to solve this issue. You use it to pass state between multiple invokations of a rule (eg. Does this `if` statement contain an `else` ?)
